#ifndef SWIG_CGAL_KERNEL_ENUM_H
#define SWIG_CGAL_KERNEL_ENUM_H

enum Oriented_side { ON_NEGATIVE_SIDE=-1, ON_ORIENTED_BOUNDARY=0, ON_POSITIVE_SIDE=1};
enum Bounded_side{ ON_UNBOUNDED_SIDE = -1,ON_BOUNDARY,ON_BOUNDED_SIDE};

#endif //SWIG_CGAL_KERNEL_ENUM_H
