name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp>=1.77.0
  - mpir
  - zlib
  - eigen
  - mpfr
  - numpy
  - twine
  - delocate
  - pycodestyle
  - swig
  - tbb
  - tbb-devel
  - wheel
  - bzip2
