#ifndef SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H
#define SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H

#include <SWIG_CGAL/Triangulation_3/triangulation_handles.h>
#include <SWIG_CGAL/Common/Input_iterator.h>


DECLARE_CIRCULATOR_CLASS(Cell_circulator)
DECLARE_CIRCULATOR_CLASS(Facet_circulator)


#endif //SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H
