#ifndef SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H
#define SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H

#include "triangulation_handles.h"
#include "../Common/Input_iterator.h"


DECLARE_CIRCULATOR_CLASS(Cell_circulator)
DECLARE_CIRCULATOR_CLASS(Facet_circulator)


#endif //SWIG_CGAL_TRIANGULATION_3_TRIANGULATION_ITERATORS_H
