name: Windows Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2016
    strategy:
      max-parallel: 4
      matrix:
        cgal_branch: [master, releases/CGAL-5.0-branch]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    #- name: Set up Python 3.7
    #  uses: actions/setup-python@v1
    #  with:
    #    python-version: 3.7

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install TBB
      run: |
        # == Install TBB ==
        $WebClient = New-Object System.Net.WebClient
        $WebClient.DownloadFile("https://github.com/intel/tbb/releases/download/v2020.1/tbb-2020.1-win.zip", "C:\tbb.zip")
        Expand-Archive C:\tbb.zip C:\tbb
        cd C:\tbb\tbb\bin\intel64\vc14
        mv tbb.dll C:\Miniconda\Library\bin
        mv tbbmalloc.dll C:\Miniconda\Library\bin
        cd C:\tbb\tbb
        mv include\* C:\Miniconda\Library\include
        mv lib\intel64\vc14\* C:\Miniconda\Library\lib

    - name: Check Install
      run: |
        ls C:/Miniconda/Library/lib
        ls C:/Miniconda/Library/bin
        ls C:/Miniconda/Library/include
      shell: bash

    - name: Setup Conda
      run: |
        echo ::add-path::C:/Miniconda/condabin;
        echo ::add-path::C:/Miniconda/Library/bin;

    - name: Install dependencies
      run: |
        conda install -y -c anaconda swig
        conda install -y -c conda-forge cgal-cpp
        python.exe -m pip install --upgrade pip
        pip install numpy
        pip install wheel


    - name: Install CGAL and other dependencies
      run: |
        cd C:\
        git clone https://github.com/CGAL/cgal.git
        cd cgal
        git checkout releases/CGAL-5.0.2
        git branch
        cd C:\
        git clone https://github.com/CGAL/LAStools.git C:\LAStools
        cd C:\LAStools
        mkdir build
        cd C:\LAStools\build
        cmake -G "Visual Studio 15 2017 Win64" C:\LAStools -DCMAKE_INSTALL_PREFIX=C:/Miniconda/Library
        cmake --build . --config Release
        cmake --install . --config Release




#    - name: Fix LAStools Install
#      run: |
#        cd C:/Miniconda/Library/include
#        mv LASzip/* ./*
#        mv LASlib/* ./*
#        rm -rf LASzip LASlib
#      shell: bash


#    - name: Build Tests
#      run: |
#        mkdir build
#        cd build
#        cmake -G "Visual Studio 15 2017" -T"v140" -A x64 -DBUILD_JAVA=ON -DBUILD_PYTHON=ON -DBUILD_TESTING=ON -DCMAKE_PREFIX_PATH="C:/Miniconda/Library"  -DBUILD_SHARED_LIBS=ON ..
#        cmake --build . --config Release
#        cmake --build . --config Release --target tests
#        echo ::add-path::D:/a/cgal-swig-bindings/cgal-swig-bindings/build/lib/Release;
#        echo ::add-path::D:/a/cgal-swig-bindings/cgal-swig-bindings/build/build-java/lib/;
#
#    - name: Run Tests
#      run: |
#        cd build
#        ctest -C Release -j8 -VV

    - name: Test Setup
      run: |
        python.exe setup.py bdist_wheel --cmake-prefix-path="C:/Miniconda/Library" --generator="Visual Studio 15 2017 Win64" --cgal-dir=C:/cgal
        pip install dist/cgal-5.0.2-cp36-cp36m-win_amd64.whl

    - name: Test Installation
      run: |
        cd examples/python
        Get-ChildItem "$PWD" |
        Foreach-Object {
          python.exe $_
        }

